import { Link } from 'react-router-dom';
import usePageMeta from '../../hooks/usePageMeta';
import DocsShell, { H2, P, Steps, Bullets, Code, Note } from './DocsShell';

export default function DocsYoutube() {
  usePageMeta({
    title: 'YouTube & 1000+ sites',
    description: 'Download from YouTube and 1000+ sites with Nexa: the quality picker, playlists, and fixing “authentication required (HTTP 403)” with the extension or Site Logins.',
  });

  return (
    <DocsShell
      title="YouTube & 1000+ sites"
      intro="Nexa drives yt-dlp under the hood, so anything yt-dlp can fetch — YouTube, Vimeo, Twitch VODs, SoundCloud, news sites and more — lands in the same queue as a normal file."
    >
      <H2 id="basics">Two ways to start</H2>
      <Bullets
        items={[
          <><strong className="text-white">Paste the URL</strong> into the app (the &ldquo;+&rdquo; button or <Code>Ctrl+V</Code> with the window focused). Nexa probes the page with yt-dlp and shows what it found.</>,
          <><strong className="text-white">Use the extension.</strong> On a supported page the floating Nexa button appears; clicking it sends the URL, your session cookies and the right headers to the app in one go. Prefer this on sites that need a login.</>,
        ]}
      />

      <H2 id="quality">Quality picker</H2>
      <P>
        Before the download starts you choose a target: 2160p, 1440p, 1080p, 720p, 480p or
        &ldquo;best available&rdquo;, plus audio-only (M4A/MP3). Nexa asks yt-dlp for the best
        video stream at or below your choice and the best audio, then merges them with the bundled
        ffmpeg into a single MP4 or MKV. Set a default in Settings &rarr; Video so you are not
        asked every time.
      </P>
      <Note>
        Very high resolutions on YouTube are often only offered as VP9 or AV1. They play fine in
        modern players; if you need H.264 for an older TV, pick 1080p or lower.
      </Note>

      <H2 id="playlists">Playlists and channels</H2>
      <P>
        Paste a playlist URL and Nexa offers to add every entry. Each video becomes its own row in
        the queue with the playlist name as a subfolder, and the app downloads several entries in
        parallel (subject to your concurrency limit — 3 on Free). Progress shows{' '}
        <Code>video 4 of 37</Code> on the playlist row while it runs. Private or members-only entries
        are skipped with a note instead of failing the whole playlist.
      </P>

      <H2 id="403">Fixing “authentication required (HTTP 403)”</H2>
      <P>
        A 403 from a media site means one of two things: the site wants you signed in (age-gated,
        members-only, purchased or private content), or the signed media URL has expired / was
        generated by a yt-dlp that is too old for the site&apos;s current player. Nexa tells the
        two apart in the error text where it can:
      </P>
      <Bullets
        items={[
          <><Code>authentication required (HTTP 403)</Code> — sign in and retry with cookies (below).</>,
          <><Code>media server refused the download (HTTP 403) — the stream URL expired or yt-dlp is out of date</Code> — this is <em>not</em> a login problem; update yt-dlp from Settings and retry.</>,
          <><Code>sign-in required — re-export cookies</Code> — YouTube&apos;s &ldquo;confirm you&apos;re not a bot&rdquo; wall; fresh cookies fix it.</>,
        ]}
      />
      <P>To give Nexa your session:</P>
      <Steps
        items={[
          <><strong className="text-white">Easiest:</strong> sign in to the site in your browser, then start the download with the extension&apos;s Nexa button. The extension exports the site&apos;s cookies through the local bridge and yt-dlp uses them for that download.</>,
          <><strong className="text-white">Without the extension:</strong> export a Netscape-format <Code>cookies.txt</Code> for the site (any &ldquo;Get cookies.txt&rdquo; browser add-on works), then in the app open <strong className="text-white">Settings &rarr; Site logins</strong> and add it for the domain. Nexa keeps one file per domain and passes it as <Code>--cookies</Code> to yt-dlp automatically.</>,
          <>Retry the download. Cookies expire; if a site starts failing again weeks later, re-export.</>,
        ]}
      />
      <Note tone="warn" title="Windows note">
        yt-dlp&apos;s own <Code>--cookies-from-browser</Code> cannot read Chrome, Edge or Brave
        cookies on Windows any more (Chrome 127+ App-Bound Encryption). The extension route is
        unaffected because it reads cookies through the browser&apos;s API.
      </Note>

      <H2 id="update">Keeping yt-dlp current</H2>
      <P>
        Sites change their players constantly and yt-dlp releases fixes within days. Settings &rarr;
        Video &rarr; <strong className="text-white">Update yt-dlp</strong> downloads the latest release into
        the app&apos;s data folder without reinstalling Nexa. If a site that used to work suddenly
        fails, try this first.
      </P>

      <P>
        Course platforms (Udemy, Coursera) have their own guide: <Link to="/docs/courses" className="text-brand-300 hover:underline">Courses</Link>.
      </P>
    </DocsShell>
  );
}
